##### Labeler ##########################################################################################################
# Enable "labeler" for your PR that would add labels to PRs based on the paths that are modified in the PR.
labelPRBasedOnFilePath:
  # Add 'label1' to any changes within 'example' folder or any subfolders
  need review:
    - "config/**"
    - ".github/**"
    - "kubejs/**"
    - "script/**"

  # Add 'label2' to any file changes within 'example2' folder
  .github:
    - ".github/**"

  resource:
    - "resourcepacks/**"
    - "resources/**"
    - "kubejs/assets/**"

  # Complex: Add 'area/core' label to any change within the 'core' package
  ftbquest:
    - "config/ftbquest/**"

  # Add 'test' label to any change to *.spec.js files within the source dir
  #test:
  #  - src/**/*.spec.js
  
# Various Flags to control behaviour of the "Labeler"
labelerFlags:
    # If this flag is changed to 'false', labels would only be added when the PR is first created and not when existing
    # PR is updated.
    # The default is 'true' which means the labels would be added when PR is updated even if they were removed by the user
    labelOnPRUpdates: true  

##### Greetings ########################################################################################################
# Comment to be posted to welcome users when they open their first PR
firstPRWelcomeComment: >
  哇！好大一只译者，抓住你了，感谢你的汉化！
# Comment to be posted to congratulate user on their first merged PR
firstPRMergeComment: >
  干的不错，下回继续，别忘了抓紧学学Github。
# Comment to be posted to on first time issues
firstIssueWelcomeComment: >
  欢迎，感谢你为整合包汉化做出的反馈，下次再来，客官您慢走。
  
###### IssueLink Adder #################################################################################################
# Insert Issue (Jira/Github etc) link in PR description based on the Issue ID in PR title.
#insertIssueLinkInPrDescription:
#   # specify the placeholder for the issue link that should be present in the description
#  descriptionIssuePlaceholderRegexp: "^Issue link: (.*)$"
#  matchers:
#    # you can have several matches - for different types of issues
#    # only the first matching entry is replaced
#    jiraIssueMatch:
#      # specify the regexp of issue id that you can find in the title of the PR
#      # the match groups can be used to build the issue id (${1}, ${2}, etc.).
#      titleIssueIdRegexp: \[(AIRFLOW-[0-9]{4})\]
#      # the issue link to be added. ${1}, ${2} ... are replaced with the match groups from the
#      # title match (remember to use quotes)
#      descriptionIssueLink: "[${1}](https://issues.apache.org/jira/browse/${1}/)"
#    docOnlyIssueMatch:
#      titleIssueIdRegexp: \[(AIRFLOW-X{4})\]
#      descriptionIssueLink: "`Document only change, no JIRA issue`"

###### Title Validator #################################################################################################
# Verifies if commit/PR titles match the regexp specified
#verifyTitles:
  # Regular expression that should be matched by titles of commits or PR
  #titleRegexp: ^(\[[A-Z,]{1,}\]|[\u4e00-\u9fa5]*|)\s*[A-Za-z\s]+\s*[\u4e00-\u9fa5]*.*$
  # If set to true, it will always check the PR title (as opposed to the individual commits).
  #alwaysUsePrTitle: true
  # If set to true, it will only check the commit in case there is a single commit.
  # In case of multiple commits it will check PR title.
  # This reflects the standard behaviour of Github that for `Squash & Merge` GitHub
  # uses the PR title rather than commit messages for the squashed commit ¯\_(ツ)_/¯
  # For single-commit PRs it takes the squashed commit message from the commit as expected.
  #
  # If set to false it will check all commit messages. This is useful when you do not squash commits at merge.
  #validateEitherPrOrSingleCommitTitle: true
  # The title the GitHub status should appear from.
  #statusTitle: "标题查验器"
  # A custom message to be displayed when the title passes validation.
  #successMessage: "查验通过！"
  # A custom message to be displayed when the title fails validation.
  # Allows insertion of ${type} (commit/PR), ${title} (the title validated) and ${regex} (the titleRegexp above).
  #failureMessage: "错误的${type}标题：${title}"

###### PR/Branch Up-To-Date Checker ####################################################################################
# Check if the branch is up to date with master when certain files are modified
#checkUpToDate:
  # The default branch is "master", change the branch if you want to check against a different target branch  
#  targetBranch: master
#  files:
  # File paths that you want to check for
  # In this example, it checks if the branch is up to date when alembic migrations are modified in the PR.
  # It helps avoid multiple heads in alembic migrations in a collaborative development project.
#    - airflow/migrations/*
#    - airflow/migrations/**/*
#    - airflow/alembic.ini
